name: Auto SemVer [Main]

on:
  pull_request:
    branches:
      - 'main'

jobs:
  auto-semver-develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump Major Version
      run: |
        CURRENT_VERSION=cat 'version.txt'
        arrVERSION=(${CURRENT_VERSION//./ })
        ((arrVERSION[1]++))
        delim=""
        joined=""
        for item in "${arrVERSION[@]}"; do
          joined="$joined$delim$item"
          delim="."
        done
        echo "$joined" > 'version.txt'
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add version.txt
        git commit -m "Chore: SemVer Bump"
        git push
