name: Auto SemVer [Main]

on:
  pull_request:
    branches:
      - 'main'

jobs:
  auto-semver-develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: "${{ secrets.APPROVE_TOKEN }}"
    - name: Bump Minor Version
      run: |
        CURRENT_VERSION=`cat version.txt`

        echo "Current Version: $CURRENT_VERSION"
        arrVERSION=(${CURRENT_VERSION//./ })
        ((arrVERSION[1]++))
        ((arrVERSION[2]=0))

        delim=""
        joined=""

        for item in "${arrVERSION[@]}"; do
        	joined="$joined$delim$item"
        	delim="."
        done

        echo "$joined" > 'version.txt'
        echo "Minor Version Bumped to $joined"
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add version.txt
        git commit -m "Chore: Version Bumped to $joined"
        git push origin HEAD:github.ref
