name: Auto Merge

on:
  pull_request:
    branches:
      - 'main'

jobs:
  auto-semver-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: "${{ secrets.APPROVE_TOKEN }}"