name: Auto SemVer [Develop]

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  auto-semver-develop:
    runs-on: ubuntu-latest
    steps:
      - if: "!contains(github.event.head_commit.message, 'Chore: Version Bumped to ') && !contains(github.event.head_commit.message, 'Chore: Version Bumped to ')"
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.pull_request.head.ref }}"
          token: "${{ secrets.APPROVE_TOKEN }}"
      - name: Bump Patch Version
        run: |
          CURRENT_VERSION=`cat version.txt`

          echo "Current Version: $CURRENT_VERSION"
          arrVERSION=(${CURRENT_VERSION//./ })
          ((arrVERSION[2]++))

          delim=""
          joined=""

          for item in "${arrVERSION[@]}"; do
              joined="$joined$delim$item"
              delim="."
          done

          echo "$joined" > 'version.txt'
          echo "Patch Version Bumped to $joined"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add version.txt
          git commit -m "Chore: Version Bumped to $joined"
          git push
